"""add column referral

Revision ID: 5f29260b8872
Revises: 7069fafcd776
Create Date: 2025-02-14 16:10:22.575370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f29260b8872"
down_revision: Union[str, None] = "7069fafcd776"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("referralcodes", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referralcodes", "is_active")
    # ### end Alembic commands ###
